sudo: required
services:
  - docker

before_install:
  - docker build -t jrodriguez10388/front -f Dockerfile.dev .


script:
  - docker run -e CI=true jrodriguez10388/front npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-146153108487"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
